framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
            sqs:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    access_key: '%env(AWS_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT_ID)%'
                    auto_setup: false
                    debug: false
                    endpoint: https://sqs.eu-west-3.amazonaws.com
                    queue_name: oc-async-poc
                    region: eu-west-3
                    secret_key: '%env(AWS_SECRET_KEY)%'
            sqs-segment:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SEGMENT)%'
                serializer: messenger.transport.custom_serializer
                options:
                    access_key: '%env(AWS_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT_ID)%'
                    auto_setup: false
                    debug: false
                    endpoint: https://sqs.eu-west-1.amazonaws.com
                    queue_name: Segment
                    region: eu-west-1
                    secret_key: '%env(AWS_SECRET_KEY)%'

        routing:
            # Route your messages to the transports
            'App\Business\Async\Message\SendInvitationMessage': sqs
            'App\Business\Async\Message\SegmentMessage': sqs-segment
